eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname:localhost

management:
  endpoints:
    web:
     exposure:
       include: "*"

spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  application:
    name: product-service
logging:
  file:
    name: product-service.log
    max-history: 20
    max-size: 20MB

